version: "3"
services:
  app:
    build: .
    depends_on:
      - mysql
    ports:
      - "8080:80"
    volumes:
      - .:/src/app
    links:
      - mysql
  mysql:
    image: "mysql:5.7.28"
    ports:
      - "13306:3306"
    environment:
      - MYSQL_DATABASE=docker
      - MYSQL_ROOT_PASSWORD=password
  phpmyadmin:
    image: "phpmyadmin/phpmyadmin:4.9.1"
    links:
      - mysql
    ports:
      - 8765:80
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql